const array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
const oddValues = array.filter((item) => item % 2 !== 0)
const evenValues = array.filter((item) => item % 2 === 0)
const isAllEven = array.every((item) => item % 2 === 0)
const isSomeOdd = array.some((item) => item % 2 !== 0)
const multipliesBy10 = array.map((item) => item * 10)
const sum = array.reduce((acc, item) => (acc += item), 0)
array.push(11)
array.pop()
array.shift()
array.unshift(10)
const slicedArray = array.slice(1, 5)
array.splice(1, 5)
console.log(array)
